// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestWord2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uIZamknijButton = this.UIKreatoraktywacjiprodWindow.UIKreatoraktywacjiprodDialog.UIZamknijButton;
            WinButton uIKartaPlikButton = this.UIDokument1MicrosoftWoWindow.UIItemWindow.UIRibbonPropertyPage.UIKartaPlikButton;
            WinMenuItem uIOpcjeMenuItem = this.UIDokument1MicrosoftWoWindow.UIPlikMenuBar.UIOpcjeMenuItem;
            WinListItem uISprawdzanieListItem = this.UIOpcjeprogramuWordWindow.UIKategorieClient.UISprawdzanieListItem;
            WinCheckBox uIIgnorujwyrazypisaneWCheckBox = this.UIOpcjeprogramuWordWindow.UIPodczaspoprawianiapiGroup.UIIgnorujwyrazypisaneWCheckBox;
            WinButton uIOKButton = this.UIOpcjeprogramuWordWindow.UIOpcjeprogramuWordDialog.UIOKButton;
            WinButton uIZamknijButton1 = this.UIDokument1MicrosoftWoWindow.UIItemWindow.UIRibbonPropertyPage.UIZamknijButton;
            #endregion

            // Launch '%ProgramW6432%\Microsoft Office\Office14\WINWORD.EXE'
            ApplicationUnderTest wINWORDApplication = ApplicationUnderTest.Launch(this.RecordedMethod1Params.ExePath, this.RecordedMethod1Params.AlternateExePath);

            // Click 'Zamknij' button
            Mouse.Click(uIZamknijButton, new Point(16, 13));

            // Click 'Karta Plik' button
            Mouse.Click(uIKartaPlikButton, new Point(14, 16));

            // Click 'Opcje' menu item
            Mouse.Click(uIOpcjeMenuItem, new Point(61, 22));

            // Click 'Sprawdzanie' list item
            Mouse.Click(uISprawdzanieListItem, new Point(48, 20));

            // Clear 'Ignoruj wyrazy pisane WIELKIMI LITERAMI' check box
            uIIgnorujwyrazypisaneWCheckBox.Checked = this.RecordedMethod1Params.UIIgnorujwyrazypisaneWCheckBoxChecked;

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(51, 15));

            // Click 'Zamknij' button
            Mouse.Click(uIZamknijButton1, new Point(47, 0));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIKreatoraktywacjiprodWindow UIKreatoraktywacjiprodWindow
        {
            get
            {
                if ((this.mUIKreatoraktywacjiprodWindow == null))
                {
                    this.mUIKreatoraktywacjiprodWindow = new UIKreatoraktywacjiprodWindow();
                }
                return this.mUIKreatoraktywacjiprodWindow;
            }
        }
        
        public UIDokument1MicrosoftWoWindow UIDokument1MicrosoftWoWindow
        {
            get
            {
                if ((this.mUIDokument1MicrosoftWoWindow == null))
                {
                    this.mUIDokument1MicrosoftWoWindow = new UIDokument1MicrosoftWoWindow();
                }
                return this.mUIDokument1MicrosoftWoWindow;
            }
        }
        
        public UIOpcjeprogramuWordWindow UIOpcjeprogramuWordWindow
        {
            get
            {
                if ((this.mUIOpcjeprogramuWordWindow == null))
                {
                    this.mUIOpcjeprogramuWordWindow = new UIOpcjeprogramuWordWindow();
                }
                return this.mUIOpcjeprogramuWordWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIKreatoraktywacjiprodWindow mUIKreatoraktywacjiprodWindow;
        
        private UIDokument1MicrosoftWoWindow mUIDokument1MicrosoftWoWindow;
        
        private UIOpcjeprogramuWordWindow mUIOpcjeprogramuWordWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Office\Office14\WINWORD.EXE'
        /// </summary>
        public string ExePath = "C:\\Program Files\\Microsoft Office\\Office14\\WINWORD.EXE";
        
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Office\Office14\WINWORD.EXE'
        /// </summary>
        public string AlternateExePath = "%ProgramW6432%\\Microsoft Office\\Office14\\WINWORD.EXE";
        
        /// <summary>
        /// Clear 'Ignoruj wyrazy pisane WIELKIMI LITERAMI' check box
        /// </summary>
        public bool UIIgnorujwyrazypisaneWCheckBoxChecked = false;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIKreatoraktywacjiprodWindow : WinWindow
    {
        
        public UIKreatoraktywacjiprodWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Kreator aktywacji produktu Microsoft Office";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "NUIDialog";
            this.WindowTitles.Add("Kreator aktywacji produktu Microsoft Office");
            #endregion
        }
        
        #region Properties
        public UIKreatoraktywacjiprodDialog UIKreatoraktywacjiprodDialog
        {
            get
            {
                if ((this.mUIKreatoraktywacjiprodDialog == null))
                {
                    this.mUIKreatoraktywacjiprodDialog = new UIKreatoraktywacjiprodDialog(this);
                }
                return this.mUIKreatoraktywacjiprodDialog;
            }
        }
        #endregion
        
        #region Fields
        private UIKreatoraktywacjiprodDialog mUIKreatoraktywacjiprodDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIKreatoraktywacjiprodDialog : WinControl
    {
        
        public UIKreatoraktywacjiprodDialog(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Kreator aktywacji produktu Microsoft Office";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
            this.WindowTitles.Add("Kreator aktywacji produktu Microsoft Office");
            #endregion
        }
        
        #region Properties
        public WinButton UIZamknijButton
        {
            get
            {
                if ((this.mUIZamknijButton == null))
                {
                    this.mUIZamknijButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIZamknijButton.SearchProperties[WinButton.PropertyNames.Name] = "Zamknij";
                    this.mUIZamknijButton.WindowTitles.Add("Kreator aktywacji produktu Microsoft Office");
                    #endregion
                }
                return this.mUIZamknijButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIZamknijButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDokument1MicrosoftWoWindow : WinWindow
    {
        
        public UIDokument1MicrosoftWoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "OpusApp";
            this.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIPlikMenuBar UIPlikMenuBar
        {
            get
            {
                if ((this.mUIPlikMenuBar == null))
                {
                    this.mUIPlikMenuBar = new UIPlikMenuBar(this);
                }
                return this.mUIPlikMenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIPlikMenuBar mUIPlikMenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Ribbon";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "NetUIHWND";
            this.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
            #endregion
        }
        
        #region Properties
        public UIRibbonPropertyPage UIRibbonPropertyPage
        {
            get
            {
                if ((this.mUIRibbonPropertyPage == null))
                {
                    this.mUIRibbonPropertyPage = new UIRibbonPropertyPage(this);
                }
                return this.mUIRibbonPropertyPage;
            }
        }
        #endregion
        
        #region Fields
        private UIRibbonPropertyPage mUIRibbonPropertyPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRibbonPropertyPage : WinControl
    {
        
        public UIRibbonPropertyPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Ribbon";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "PropertyPage";
            this.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
            #endregion
        }
        
        #region Properties
        public WinButton UIKartaPlikButton
        {
            get
            {
                if ((this.mUIKartaPlikButton == null))
                {
                    this.mUIKartaPlikButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIKartaPlikButton.SearchProperties[WinButton.PropertyNames.Name] = "Karta Plik";
                    this.mUIKartaPlikButton.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
                    #endregion
                }
                return this.mUIKartaPlikButton;
            }
        }
        
        public WinButton UIZamknijButton
        {
            get
            {
                if ((this.mUIZamknijButton == null))
                {
                    this.mUIZamknijButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIZamknijButton.SearchProperties[WinButton.PropertyNames.Name] = "Zamknij";
                    this.mUIZamknijButton.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
                    #endregion
                }
                return this.mUIZamknijButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIKartaPlikButton;
        
        private WinButton mUIZamknijButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPlikMenuBar : WinMenuBar
    {
        
        public UIPlikMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Plik";
            this.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIOpcjeMenuItem
        {
            get
            {
                if ((this.mUIOpcjeMenuItem == null))
                {
                    this.mUIOpcjeMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIOpcjeMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Opcje";
                    this.mUIOpcjeMenuItem.WindowTitles.Add("Dokument1 - Microsoft Word (Aktywacja produktu nie powiodła się)");
                    #endregion
                }
                return this.mUIOpcjeMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIOpcjeMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpcjeprogramuWordWindow : WinWindow
    {
        
        public UIOpcjeprogramuWordWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Opcje programu Word";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "NUIDialog";
            this.WindowTitles.Add("Opcje programu Word");
            #endregion
        }
        
        #region Properties
        public UIKategorieClient UIKategorieClient
        {
            get
            {
                if ((this.mUIKategorieClient == null))
                {
                    this.mUIKategorieClient = new UIKategorieClient(this);
                }
                return this.mUIKategorieClient;
            }
        }
        
        public UIPodczaspoprawianiapiGroup UIPodczaspoprawianiapiGroup
        {
            get
            {
                if ((this.mUIPodczaspoprawianiapiGroup == null))
                {
                    this.mUIPodczaspoprawianiapiGroup = new UIPodczaspoprawianiapiGroup(this);
                }
                return this.mUIPodczaspoprawianiapiGroup;
            }
        }
        
        public UIOpcjeprogramuWordDialog UIOpcjeprogramuWordDialog
        {
            get
            {
                if ((this.mUIOpcjeprogramuWordDialog == null))
                {
                    this.mUIOpcjeprogramuWordDialog = new UIOpcjeprogramuWordDialog(this);
                }
                return this.mUIOpcjeprogramuWordDialog;
            }
        }
        #endregion
        
        #region Fields
        private UIKategorieClient mUIKategorieClient;
        
        private UIPodczaspoprawianiapiGroup mUIPodczaspoprawianiapiGroup;
        
        private UIOpcjeprogramuWordDialog mUIOpcjeprogramuWordDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIKategorieClient : WinClient
    {
        
        public UIKategorieClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Opcje programu Word");
            #endregion
        }
        
        #region Properties
        public WinListItem UISprawdzanieListItem
        {
            get
            {
                if ((this.mUISprawdzanieListItem == null))
                {
                    this.mUISprawdzanieListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUISprawdzanieListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Sprawdzanie";
                    this.mUISprawdzanieListItem.WindowTitles.Add("Opcje programu Word");
                    #endregion
                }
                return this.mUISprawdzanieListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUISprawdzanieListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPodczaspoprawianiapiGroup : WinGroup
    {
        
        public UIPodczaspoprawianiapiGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Podczas poprawiania pisowni w programach pakietu Microsoft Office";
            this.WindowTitles.Add("Opcje programu Word");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UIIgnorujwyrazypisaneWCheckBox
        {
            get
            {
                if ((this.mUIIgnorujwyrazypisaneWCheckBox == null))
                {
                    this.mUIIgnorujwyrazypisaneWCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIIgnorujwyrazypisaneWCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Ignoruj wyrazy pisane WIELKIMI LITERAMI";
                    this.mUIIgnorujwyrazypisaneWCheckBox.WindowTitles.Add("Opcje programu Word");
                    #endregion
                }
                return this.mUIIgnorujwyrazypisaneWCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUIIgnorujwyrazypisaneWCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpcjeprogramuWordDialog : WinControl
    {
        
        public UIOpcjeprogramuWordDialog(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Opcje programu Word";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
            this.WindowTitles.Add("Opcje programu Word");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Opcje programu Word");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
